### ISSUE TITLE
Book reviews

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/RadioTaxiProject#2]
Book reviews need to be in two paragraph format. The first paragraph, in less than 10 sentences, summarizes the major technical lessons of the book that are relevant to the project.

The second paragraph, in less than 4 sentences, gives an outline of chapters/sections that need to be read for successful project implementation.

**Comment by nisargshah95** [comment]
Book reviews have been [modified](../wiki/Book-Reviews). I could not write more for the first paragraph for each review as I have read very little part of the book.
