### ISSUE TITLE
CI-CD setup

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/RadioTaxiProject#4]
The setup on Amazon for continuous integration and continuous deployment. The appropriate links to the application can be posted on the README.md of the main repository.

**Comment by prasadtalasila** [comment]
The deployable war file can be automatically put in bin/ directory of the development branch (I think Jenkins has to do this). 

The installation script that takes a configuration file and deploys the Tomcat context, war file must also be in the bin/ directory.

**Comment by nisargshah95** [comment]
Sir can you go to the repository settings -> Webhooks & Services -> Add service, select Jenkins and add the following Jenkins hook url - http://ec2-54-179-158-124.ap-southeast-1.compute.amazonaws.com:8080/github-webhook/

**Comment by prasadtalasila** [comment]
The webhook has been installed. Please post the links to the live application on the Wiki home page.

**Comment by nisargshah95** [comment]
Jenkins is set up to automatically build when a new commit is made and the war file is being created successfully. But I could not find a way to deploy the war file in tomcat from within the bin directory.

**Comment by nisargshah95** [comment]
The only issue remaining is the fact that tomcat does not seem to reload the updated war file automatically and needs to be restarted.

**Comment by nisargshah95** [comment]
The project has been hosted at http://10.1.9.209:8081/RadioTaxi/. I will put up docs related to deployment shortly. We are running Cassandra as a stand-alone application, rather than a process.
