### ISSUE TITLE
Tomcat classpath issue (jar loading problem)

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/RadioTaxiProject#6]
Tomcat can't load the required libraries. This is usually a sign of incorrectly setup CLASSPATH for the tomcat web application.

A tutorial page for correctly setting up the CLASSPATH inside Tomcat is https://www.mulesoft.com/tcat/tomcat-classpath

**Comment by nisargshah95** [comment]
Solved - Put the jars in WebContent/WEB-INF/lib directory. Better alternative is to use Maven.
