### ISSUE TITLE
Storing session state in JSP controller

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/RadioTaxiProject#7]
What is the best way to store the session state in JSP pages on the server-side?

**Comment by prasadtalasila** [comment]
The solution seems to be fairly straight forward. Please see the following links.
1. http://www.journaldev.com/1907/java-servlet-session-management-tutorial-with-examples-of-cookies-httpsession-and-url-rewriting
2. Chapter 11: Session Tracking, Java Servlet & JSP Cookbook, Bruce W. Perry, O'Reilly Publishers
3. http://www.javatpoint.com/servlet-http-session-login-and-logout-example

**Comment by nisargshah95** [comment]
The first link itself was sufficient to get the job done. Session states are now being maintained using HttpSession.
